### ISSUE TITLE
Do something about scroll overflow in results

### ISSUE THREAD

**Issue by ericawright** [ericawright/lockbox-test#11]
![screen shot 2018-01-23 at 4 33 33 pm](https://user-images.githubusercontent.com/10803178/35302051-3c95e4ea-005b-11e8-973c-a2d5b6bdf673.png)

**Comment by ericawright** [comment]
@changecourse I'm not sure what to do here. Because of the image, I can't really make the input field multi-lined...

**Comment by changecourse** [comment]
Though this is a legitimate issue for us to figure out longterm, I'm not as worried about this situation occurring during our moderated sessions... I'd say that for now we just hide the x-overflow/scrollbar and allow it to extend past the field.
