### ISSUE TITLE
Inputs on Windows are slightly misaligned…

### ISSUE THREAD

**Issue by bwinton** [ericawright/lockbox-test#12]
![here](https://cl.ly/0T3p0g1Y0P3t/Image%202018-01-24%20at%2010.21.07%20AM.png)

**Comment by ericawright** [comment]
I made them larger, i think it fixed it. please check

**Comment by bwinton** [comment]
Better, but they're not quite wide enough, and don't have the border radius…
![this](https://d2ffutrenqvap3.cloudfront.net/items/3d2y1E091G2q250s1j1v/Image%202018-01-25%20at%209.55.00%20AM.png)

**Comment by ericawright** [comment]
now should be fixed
