### ISSUE TITLE
Inverse active and hover state of + button in doorhanger

### ISSUE THREAD

**Issue by changecourse** [ericawright/lockbox-test#13]
Can we have the default state of the + button be full opacity opacity blue, and then add the lighter tint (or a lighter shade of moz-blue) for the hover state? 

<img width="385" alt="screen shot 2018-01-24 at 1 39 58 pm" src="https://user-images.githubusercontent.com/6164801/35355953-3f296c34-010c-11e8-86a7-6ddb647920a0.png">

**Comment by ericawright** [comment]
I can change it to be the photon button colors. that's what I'm in the process of doing for the continue buttons etc.

https://design.firefox.com/photon/components/buttons.html#primary-3

**Comment by changecourse** [comment]
Sounds good... wait, didn't I provide buttons on the doorhangers with the appropriate blue60 color? Or are you having to overlay over the top of them in order to ensure the appropriate functionality?

**Comment by ericawright** [comment]
yeah, the colors are a little different than what was provided. it doesn't matter though, since I need to use the hover and active effects, I need to overlay it anyway
