### ISSUE TITLE
Website Address field not inheriting the same style as other fields... 

### ISSUE THREAD

**Issue by changecourse** [ericawright/lockbox-test#14]
Border box styling differences for that field. See below: 

<img width="370" alt="screen shot 2018-01-24 at 1 41 30 pm" src="https://user-images.githubusercontent.com/6164801/35356013-6ff091a8-010c-11e8-90a1-8a599a383ff2.png">

**Comment by changecourse** [comment]
This is also the case for mismatching in styling of the borders for the paragraph field (notes) vs. single-line fields

**Comment by ericawright** [comment]
wow, I haven't seen that. what OS are you on?

**Comment by changecourse** [comment]
I've been using nightly... 

Actually, I figured it out... this is caused by Lastpass sniffing out some of the fields for autofill prompts... which apparently changes their styling slightly... disabling the add-on fixed this. Feel free to close.
