### ISSUE TITLE
Raster imagery looks blurry/pixelated compared to HTML

### ISSUE THREAD

**Issue by changecourse** [ericawright/lockbox-test#15]
Not sure if there's an easy solve for this or not (maybe retina support and 2x imagery?) but the text readability associated with the png source images is different than the programmatically generated text (questions and links)

<img width="374" alt="screen shot 2018-01-24 at 1 45 16 pm" src="https://user-images.githubusercontent.com/6164801/35356249-11f1b400-010d-11e8-910d-b12497b56f98.png">

**Comment by ericawright** [comment]
yeah, we noticed that too. we can try with 2x images? not sure how else to fix it...

**Comment by ericawright** [comment]
or, I can just write text on top of all the text in the image, so at least it will all be equally sharp

**Comment by changecourse** [comment]
Whichever would be easiest... happy to provide 2x imagery if needed.

**Comment by ericawright** [comment]
@changecourse I wrote on top of most of them, let me know what you think?

**Comment by changecourse** [comment]
I think we're good to not worry about 2x density with the latest addition of HTML text.
