### ISSUE TITLE
Padding on input fields

### ISSUE THREAD

**Issue by changecourse** [ericawright/lockbox-test#16]
For both the placeholder text, and the entered text, can we have 8px of left-padding so it isn't scrunched up to the edge of the field?

<img width="304" alt="screen shot 2018-01-24 at 1 47 40 pm" src="https://user-images.githubusercontent.com/6164801/35356319-49d690ca-010d-11e8-8d8e-8176834acd94.png">
<img width="284" alt="screen shot 2018-01-24 at 1 47 46 pm" src="https://user-images.githubusercontent.com/6164801/35356320-49ebbbd0-010d-11e8-99a6-38b798751e7c.png">

**Comment by ericawright** [comment]
done
