### ISSUE TITLE
Placement of words/characters toggle

### ISSUE THREAD

**Issue by changecourse** [ericawright/lockbox-test#17]
Raising up the placement of the toggle to better sit between the header bar and the generated password field. (Decreasing the margin on #header to 6px)

Also the font weight adjustment for the links in the toggle. 

<img width="325" alt="screen shot 2018-01-24 at 1 56 49 pm" src="https://user-images.githubusercontent.com/6164801/35356746-8ed228be-010e-11e8-93ce-95498ed4fc84.png">

<img width="343" alt="screen shot 2018-01-24 at 1 56 55 pm" src="https://user-images.githubusercontent.com/6164801/35356747-8f10dc9e-010e-11e8-8a55-f490e96976c8.png">

**Comment by ericawright** [comment]
done

**Comment by ericawright** [comment]
@changecourse by font weight.... do you mean it should be more bold?

**Comment by changecourse** [comment]
yes, ideally, to match the comps... not sure if default is 300 or 500... but maybe add 200 more than whatever it currently is?
