### ISSUE TITLE
Learn More

### ISSUE THREAD

**Issue by ericawright** [ericawright/lockbox-test#18]
@changecourse
should learn more be clickable, and if so, where does it link to?
![screen shot 2018-01-25 at 3 28 47 pm](https://user-images.githubusercontent.com/10803178/35410780-7a03faa8-01e4-11e8-9b65-36910b5404b6.png)

**Comment by ericawright** [comment]
Since I'm writing out the text again, I can also remove it quite easily

**Comment by changecourse** [comment]
Let's remove the link for now. Thanks!
