### ISSUE TITLE
Change start of prototype to be the expanded "Create Password" doorhanger already open

### ISSUE THREAD

**Issue by changecourse** [ericawright/lockbox-test#21]
After discussions with UR and Product, we're minimizing the scope of our effort to focus on the PW Generation experience. Therefore, we'd like the prototype to start on this screen, rather than having the user click the icon, as well as the plus button for the entry list.

![create new](https://user-images.githubusercontent.com/6164801/35584886-98736d48-05b3-11e8-9751-2f37b2a3c32b.png)

**Comment by ericawright** [comment]
Ok, does that mean the back button on this page is disabled? After generating the PW do you want to go to the save screen and the final dismiss screen still?

**Comment by changecourse** [comment]
Back button can be removed for this particular screen since it's now the landing page. 

![3 dh_prompt_btnenabled](https://user-images.githubusercontent.com/6164801/35635190-d6a0f736-066a-11e8-959b-d236d4a448fd.png)


After generating the password, clicking on "Use this Password" should now close the doorhanger and 'reset' the experience, instead of seeing the completed form or the confirmation. 

Ideally we would also like to have global functionality of the doorhanger icon, where if it was clicked at any time (while the doorhanger was open) it would close the doorhanger and return you to the intuit screen. Clicking on the icon from that screen would then reset and open you on the initial "Create Password" question screen. [EDIT: I think this functionality already exists, just want to confirm]

**Comment by ericawright** [comment]
done, though you should test this to make sure it is how you want it.
