### ISSUE TITLE
Change copy of intro prompt for questions

### ISSUE THREAD

**Issue by changecourse** [ericawright/lockbox-test#25]
Change to: "We'll use your answer to the question below to generate a strong password. Learn More"

![intro copy](https://user-images.githubusercontent.com/6164801/35595024-87245970-05d2-11e8-8a11-b2ac675f3ba3.png)

**Comment by ericawright** [comment]
@changecourse do you want "learn more" here? we'd previously removed it since we don't know where it will link to.

**Comment by ericawright** [comment]
the text is significantly shorter, would you like the text to be larger, or can you provide me with a new image with a smaller dark grey area at the top?
![screen shot 2018-01-31 at 10 05 40 am](https://user-images.githubusercontent.com/10803178/35630097-698504b8-066e-11e8-8e3b-3f073fbf7e12.png)

**Comment by changecourse** [comment]
Let's display the Learn More link, even though we won't have it go anywhere, so we can elicit discussion during the moderated sessions if people want to hypothesize about what info could be displayed (I'm less worried about this now that we're doing these moderated)

Here's the shorter image doorhanger.

![3 dh_prompt_btnenabled](https://user-images.githubusercontent.com/6164801/35634769-b1e11d50-0669-11e8-9d29-0136daf61e6c.png)

**Comment by ericawright** [comment]
ty. done
