### ISSUE TITLE
Cursor should change to "pointer" when hovering over the "Characters" (or "Words") links.

### ISSUE THREAD

**Issue by bwinton** [ericawright/lockbox-test#7]

**Comment by changecourse** [comment]
@bwinton do we have a definitive or declarative stance on this, photon-wide? I've seen it handled differently all across the browser, internal prefs, and add-ons...

**Comment by bwinton** [comment]
That would be a question for the people in #dsg, but in general, I think we want things that look (and more importantly act) like links to have the cursor associated with links…

**Comment by changecourse** [comment]
Agreed... I'll follow up with them separately, but let's go ahead and change the pointer styling to reflect this...

**Comment by changecourse** [comment]
Received direction from Amin regarding cursor styles...

Links receive the pointer, everything else retains default styling. 

Can we add the pointer for all links?

**Comment by ericawright** [comment]
done
